name: Storinator9000
main: me.ccgreen.Storinator.StorinatorMain
version: 1.0.0
description: A vault plugin
depend: [SQLlib]
api-version: 1.15

commands:
  storinator:
    description: the main vault command
permissions:
  Storinator.access:
    default: true
  Storinator.vault.1:
    default: true
  Storinator.vault.2:
    default: true
  Storinator.vault.3:
    default: true
  Storinator.vault.4:
    default: false
  Storinator.vault.5:
    default: false
  Storinator.vault.6:
    default: false
  Storinator.vault.7:
    default: false
  Storinator.vault.8:
    default: false